### PR TITLE
4 new schemes

### PR DESCRIPTION
**Pull request by notklaatu**
borderlands
kingdoms of amalur
xbox generic
sega genesis emu

### CODE REVIEW

**Comment by jsbackus** [comment]
Looks good! Thanks! Merged.

**Comment by jsbackus** [comment]
Forgot to ask: Do we have your permission to distribute these profiles under the [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html)

**Comment by notklaatu** [comment]
Of course! GPLv3's my favourite license!

**Comment by jsbackus** [comment]
Great! Thanks!

**Pull request merged**
