### PR TITLE
Add profile for "Where is my Heart?"

### PR DESCRIPTION
**Pull request by riophae**

### CODE REVIEW

**Comment by jsbackus** [comment]
Hi @riophae, thanks for the contribution! How would you like to be listed in the CREDITS.txt?

**Comment by jsbackus** [comment]
Also, in the future, please don't compress the files. Simply add the ASCII versions. I've taken care of these files. Thanks!

**Comment by riophae** [comment]
@jsbackus Riophae Lee will be good.

**Comment by riophae** [comment]
Got it!

**Comment by riophae** [comment]
Should I re-edit my commits and create a new pull request?

**Comment by jsbackus** [comment]
Hi @riophae, nope, no need. I've merged it in. Thanks for the contribution!

**Comment by riophae** [comment]
Okay. Thank you!

**Pull request closed without merging**
