### PR TITLE
AntiMicro Profile - Guild Wars 2

### PR DESCRIPTION
**Pull request by jcdenton2k**
My AntiMicro Profile for Guild Wars 2 based on the general image/layout created by Patrick Roeder:  http://blog.patrgames.com/p/guild-wars-2.html and tweaked for my personal use along with my own custom keybind layout and adapted to AntiMicro instead of Xpadder.

### CODE REVIEW

**Comment by jcdenton2k** [comment]
It is a bit difficult to determine what to do since there are no obvious XML files present in the AntiMicro profile directory.  It is just the "GameName.gamecontroller.amgp" file that holds the profile information for AntiMicro.  Apparently opening this up with a text editor reveals that it is just an XML file.

I've also included the image along with attribution to the original layout that I modified and adapted for AntiMicro.

Relevant reddit post I made: https://www.reddit.com/r/Guildwars2/comments/51uk51/guild_wars_2_wxbox_360_controller/

**Comment by jcdenton2k** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<gamecontroller configversion="19" appversion="2.22">
    
    <sdlname>XInput Controller</sdlname>
    
    <guid>78696e70757401000000000000000000</guid>
    <names/>
    <sets>
        <set index="1">
            <stick index="1">
                <stickbutton index="5">
                    <slots>
                        <slot>
                            <code>0x44</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="7">
                    <slots>
                        <slot>
                            <code>0x53</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="1">
                    <slots>
                        <slot>
                            <code>0x45</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="3">
                    <slots>
                        <slot>
                            <code>0x46</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
            </stick>
            <stick index="2">
                <diagonalRange>65</diagonalRange>
                <stickbutton index="5">
                    <slots>
                        <slot>
                            <code>2</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="7">
                    <slots>
                        <slot>
                            <code>3</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="1">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="3">
                    <slots>
                        <slot>
                            <code>4</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
            </stick>
            <dpad index="1">
                <dpadbutton index="4">
                    <slots>
                        <slot>
                            <code>0x1000015</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
                <dpadbutton index="1">
                    <slots>
                        <slot>
                            <code>0x1000013</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
                <dpadbutton index="2">
                    <slots>
                        <slot>
                            <code>0x1000014</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
                <dpadbutton index="8">
                    <slots>
                        <slot>
                            <code>0x1000012</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
            </dpad>
            <trigger index="1">
                <throttle>positivehalf</throttle>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>mousebutton</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <trigger index="2">
                <throttle>positivehalf</throttle>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>0x52</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <button index="1">
                <slots>
                    <slot>
                        <code>0x41</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="2">
                <slots>
                    <slot>
                        <code>0x42</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="3">
                <slots>
                    <slot>
                        <code>0x58</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="4">
                <slots>
                    <slot>
                        <code>0x59</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="5">
                <slots>
                    <slot>
                        <code>0x1000023</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="6">
                <slots>
                    <slot>
                        <code>0x47</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="7">
                <slots>
                    <slot>
                        <code>0x54</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="8">
                <slots>
                    <slot>
                        <code>0x49</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="9">
                <slots>
                    <slot>
                        <code>0x55</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="10">
                <slots>
                    <slot>
                        <code>0x1000021</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="11">
                <slots>
                    <slot>
                        <code>0x1000020</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
        </set>
    </sets>
</gamecontroller>
`

**Comment by jcdenton2k** [comment]
> <?xml version="1.0" encoding="UTF-8"?>
<gamecontroller configversion="19" appversion="2.22">
    
    <sdlname>XInput Controller</sdlname>
    
    <guid>78696e70757401000000000000000000</guid>
    <names/>
    <sets>
        <set index="1">
            <stick index="1">
                <stickbutton index="5">
                    <slots>
                        <slot>
                            <code>0x44</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="7">
                    <slots>
                        <slot>
                            <code>0x53</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="1">
                    <slots>
                        <slot>
                            <code>0x45</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="3">
                    <slots>
                        <slot>
                            <code>0x46</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </stickbutton>
            </stick>
            <stick index="2">
                <diagonalRange>65</diagonalRange>
                <stickbutton index="5">
                    <slots>
                        <slot>
                            <code>2</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="7">
                    <slots>
                        <slot>
                            <code>3</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="1">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
                <stickbutton index="3">
                    <slots>
                        <slot>
                            <code>4</code>
                            <mode>mousemovement</mode>
                        </slot>
                    </slots>
                </stickbutton>
            </stick>
            <dpad index="1">
                <dpadbutton index="4">
                    <slots>
                        <slot>
                            <code>0x1000015</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
                <dpadbutton index="1">
                    <slots>
                        <slot>
                            <code>0x1000013</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
                <dpadbutton index="2">
                    <slots>
                        <slot>
                            <code>0x1000014</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
                <dpadbutton index="8">
                    <slots>
                        <slot>
                            <code>0x1000012</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </dpadbutton>
            </dpad>
            <trigger index="1">
                <throttle>positivehalf</throttle>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>mousebutton</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <trigger index="2">
                <throttle>positivehalf</throttle>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>0x52</code>
                            <mode>keyboard</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <button index="1">
                <slots>
                    <slot>
                        <code>0x41</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="2">
                <slots>
                    <slot>
                        <code>0x42</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="3">
                <slots>
                    <slot>
                        <code>0x58</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="4">
                <slots>
                    <slot>
                        <code>0x59</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="5">
                <slots>
                    <slot>
                        <code>0x1000023</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="6">
                <slots>
                    <slot>
                        <code>0x47</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="7">
                <slots>
                    <slot>
                        <code>0x54</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="8">
                <slots>
                    <slot>
                        <code>0x49</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="9">
                <slots>
                    <slot>
                        <code>0x55</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="10">
                <slots>
                    <slot>
                        <code>0x1000021</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
            <button index="11">
                <slots>
                    <slot>
                        <code>0x1000020</code>
                        <mode>keyboard</mode>
                    </slot>
                </slots>
            </button>
        </set>
    </sets>
</gamecontroller>

**Comment by jcdenton2k** [comment]
Ok so if you want the XML you just rename the extension to .XML apparently.  That is pretty confusing for those who aren't familiar with file types.  If it is an XML then why not just keep the extension as .XML

**Comment by jsbackus** [comment]
Hi! Sorry for just now getting back to you. Yeah, not entirely sure why the original developer chose to use a different extension. The distinct extension does allow us to associate it with AntiMicro, so double-clicking on the .amgp file will open AntiMicro.

Thanks for your contribution! Are you ok with us distributing it under the GPLv3?

**Comment by jcdenton2k** [comment]
Absolutely!

I hereby officially release my GW2 profile contribution under the public domain.  You may also distribute it under GPLv3 or any other compatible license.

I would just like to see more GW2 players have an easier time with playing the game with a gamepad with the addition of the 'Action Combat' camera into the official game itself (no 3rd party mods required).

**Comment by jsbackus** [comment]
Great! Thanks! Merged in commit 459360b

**Pull request closed without merging**
